#
#	Makefile for 'Bignums'	(c) C. Jullien
#	$Id: makefile.nt,v 1.56 2015/01/01 08:59:10 jullien Exp $
#

.SUFFIXES: .lsp .dat .$(SUFFIXES)

!if "$(CPU)" == ""
# set CPU from $(CC) version found in path.
!if [$(CC) 2>&1 | find "x86" > nul] == 0
CPU		= i386
ANALYSE		= -analyze:WX- # -D_DEBUG -D_WINDEBUG -MTd
!elseif [$(CC) 2>&1 | find "x64" > nul] == 0
CPU		= AMD64
ANALYSE		= # -D_DEBUG -D_WINDEBUG -MTd
!elseif [$(CC) 2>&1 | find "Itanium" > nul] == 0
CPU		= IA64
ANALYSE		=
!elseif [$(CC) 2>&1 | find "ARM" > nul] == 0
CPU		= ARM
ANALYSE		=
!else
CPU		= i386
ANALYSE		= -analyze:WX-
!endif
!message Compiling using $(CC) for $(CPU) cpu.
!endif

CC		= cl
DEBUG		= -Zi
CFLAGS		= $(DEBUG) $(ANALYSE) -nologo -W4 -wd6386 -EHsc -Gs -I.
CLISP		= ccl
OLISP		= ..\ntalisp-$(CPU).exe
OBJECT		= bztest.obj bigq.obj bigz.obj bign.obj
VERSION		= 1.5.6

all: bztest.exe testkern.exe tCBignum.exe testbign.lsp # testrtnl.lsp

.c.obj:
	@$(CC) -c $(CFLAGS) -Tp $*.c

.cpp.obj:
	@$(CC) -c $(CFLAGS) $*.cpp

# KerN test

testkern.exe: bigz.obj bign.obj testkern.obj
	@$(CC) $(CFLAGS) -Fotestkern testkern.obj bigz.obj bign.obj

testkern.obj: test\testkern.c
	@$(CC) -c -Itest $(CFLAGS) test\testkern.c

# BZ test

bztest.exe: $(OBJECT)
	@$(CC) $(CFLAGS) -Fobztest.exe bztest.obj bigz.obj bign.obj

bztest.obj: test\bztest.c
	@$(CC) -c -I. -Itest $(CFLAGS) test\bztest.c

# C++ test

tCBignum.exe: bigq.obj bigz.obj bign.obj CBignum.obj CRational.obj tCBignum.obj
	@$(CC) $(CFLAGS) -FotCBignum tCBignum.obj CBignum.obj CRational.obj \
		bigq.obj bigz.obj bign.obj

tCBignum.dat: ./lisp/gentest.lsp
	@echo generating tests with $(CLISP)..
	@$(CLISP) ./lisp/gentest.lsp > tCBignum.dat
	@dos2unix -q tCBignum.dat

tCBignum.obj: CBignum.h tCBignum.dat
CRational.obj: CRational.h CRational.cpp bigz.h bign.h bigq.h

testbign.lsp: ./lisp/lisptests.lsp $(OLISP)
	@$(CLISP) ./lisp/lisptests.lsp | dos2unix > testbign.lsp
	@copy testbign.lsp $(OPENLISP)\tst\testbign.lsp > nul
	@$(OLISP) -e "(run-test \"../../tst/testbign.lsp\")"

testrtnl.lsp: ./lisp/lisprtnl.lsp $(OLISP)
	@$(CLISP) ./lisp/lisprtnl.lsp | dos2unix > testrtnl.lsp
	@copy testrtnl.lsp $(OPENLISP)\tst\testrtnl.lsp > nul
	@$(OLISP) -e "(run-test \"../../tst/testrtnl.lsp\")"

# Misc

qualify:
	@cd .. && nmake -nologo && cd bignum
	@nmake -nologo \
	       && nmake -nologo lint \
	       && testkern a \
	       && bztest \
	       && tCBignum

clean:
	-del *~ *.exe *.obj *.o *.pdb *.ilk *.BAK *.cgl *pure.log *pure.ini /s

lint:
#	set LARCH_PATH=/usr/share/splint/lib
#	Very strict rules for kernel
	@splint +quiet			\
		-checks 		\
		-exportlocal 		\
		-infloopsuncon		\
		-namechecks 		\
	        bign.c
#	Check bigz.c and (again) bign.c
	@splint +quiet			\
		-checks 		\
		-branchstate 		\
		-compdef 		\
		-exportlocal		\
		-infloopsuncon		\
		-namechecks		\
		-nullret 		\
		-retalias 		\
		-statictrans 		\
		-observertrans		\
		-temptrans 		\
		-usedef			\
	        bigz.c bign.c
	@splint +quiet			\
		-checks 		\
		-branchstate 		\
		-compdef 		\
		-declundef		\
		-exportlocal 		\
		-infloopsuncon		\
		-namechecks 		\
		-nullret 		\
		-mustfreefresh 		\
		-realcompare		\
		-realrelatecompare	\
		-temptrans 		\
	        bigq.c

CPPLINT		= /usr/local/bin/cpplint.py

cpplint:
	@bash -c "$(CPPLINT) --extensions=h,c --filter=-readability/casting big?.c"
	@bash -c "@$(CPPLINT) --filter=-build/header_guard,build/c++11 C*.h"


MASTER		= \
		AUTHORS			      \
		COPYING			      \
		ChangeLog		      \
		LICENSE			      \
		NEWS			      \
		README			      \
		autogen.sh		      \
		bign.c			      \
		bign.h			      \
		bigq.c			      \
		bigq.h			      \
		bigz.c			      \
		bigz.h			      \
		bzf.c			      \
		bignum.pc.in		      \
		bignum.spec.in		      \
		CBignum.cpp		      \
		CBignum.h		      \
		CRational.cpp		      \
		CRational.h		      \
		conf/config.guess	      \
		conf/config.sub		      \
		conf/COPYING		      \
		conf/install-sh		      \
		config.h.in		      \
		configure		      \
		configure.ac		      \
		doc/bn.html		      \
		doc/bn.tex		      \
		doc/bnbody.html		      \
		doc/bnbody.tex		      \
		doc/bnf.html		      \
		doc/bnf.tex		      \
		etc/hextable.c		      \
		etc/maxbase10.c		      \
		etc/maxbase10.lsp	      \
		etc/testbits.c		      \
		lisp/gentest.lsp	      \
		lisp/lisptests.lsp	      \
		lisp/lisprtnl.lsp	      \
		pdf/PRL-RR-2.pdf	      \
		pdf/RR-1016.pdf		      \
		pdf/RR-1016.ps		      \
	        m4/ax_check_compile_flag.m4   \
		Makefile.in		      \
		makefile.clang		      \
		makefile.gnu		      \
		makefile.lcc		      \
		makefile.nt		      \
		makefile.tcc		      \
		tCBignum.cpp		      \
		tCBignum.dat		      \
		tCBignum.dat		      \
		test/BntoBnn.h		      \
		test/bztest.c		      \
		test/testkern.c

save:
	@if exist bignum-$(VERSION).tar.gz del bignum-$(VERSION).tar.gz
	@touch bignum-$(VERSION).tar.gz
	@tar -czf bignum-$(VERSION).tar.gz $(MASTER)
	@mkdir bignum-$(VERSION) \
		&& cd bignum-$(VERSION) \
		&& tar xzf ../bignum-$(VERSION).tar.gz \
		&& cd .. \
		&& tar czf bignum-$(VERSION).tar.gz bignum-$(VERSION) \
		&& rm -r -f bignum-$(VERSION)
	@tar tvzf bignum-$(VERSION).tar.gz

tosvn:
	@for %%i in ($(MASTER)) do @echo bigz/%%i && cp %%i bigz/%%i
